### ISSUE TITLE
Use jQuery's $.ajax()?

### ISSUE THREAD

**Issue by developius** [musicboyben/chess#2]
Suggestion:
Instead of your `ajaxFunction()` just use [`$.ajax()`](http://api.jquery.com/jquery.ajax/)? It's really  easy and you don't have to do any of the header stuff - all handled by `$.ajax()` for you!

**Comment by bengineer19** [comment]
I appreciate the thought but I prefer it this way; thanks though!

**Comment by developius** [comment]
No need to check for IE etc... :smile_cat:

**Comment by bengineer19** [comment]
I know, but I like building it manually.
